# Example git-ignored dockerfile to build on top of the default user image.
# Copy this to dockerfile.user and modify as desired.

ARG BASE_IMAGE

FROM $BASE_IMAGE

# Install common development tools.
RUN apt update && apt install -y \
    vim \
    tmux \
    && rm -rf /var/lib/apt/lists/*

# Install docker into the image so we can run pre-commit utilities.
RUN install -m 0755 -d /etc/apt/keyrings && \
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc && \
    chmod a+r /etc/apt/keyrings/docker.asc && \
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
          $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
          tee /etc/apt/sources.list.d/docker.list > /dev/null && \
    apt update && \
    apt install -y docker-ce

