# Dockerfile defining a common layer on top of the base image to reduce some
# friction and add missing graphics libraries.

ARG BASE_IMAGE

FROM $BASE_IMAGE

ARG USER
ARG HOME
ARG UID
ARG GID

# Colorize the prompt.
ENV TERM xterm-256color

# Bake user and group ID into the image.
RUN groupadd --gid $GID $USER && \
    useradd -l --uid $UID --gid $GID -m $USER -s /usr/bin/zsh

# Modify the prompt so the user knows when they're in a container.
RUN echo "docker-dev" > /etc/debian_chroot

# Require no password for sudo access.
# This exposes a big security threat: when a user is added to the docker group,
# anyone with access to the machine can get root access to the filesystem through
# docker!
RUN echo "$USER ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

# Install additional graphics libraries.
RUN apt update && apt install -y \
    mesa-utils \
    libgl1-mesa-glx \
    libxcursor-dev \
    libxrandr-dev \
    libxi-dev && \
    rm -rf /var/lib/apt/lists/*

# Install common utilities
RUN apt update && apt install -y \
    curl \
    ca-certificates \
    bash-completion \
    shellcheck && \
    rm -rf /var/lib/apt/lists/*

# Docker-in-docker for pre-commit things.
COPY docker_install.sh /docker_install.sh
RUN /docker_install.sh

# Some ugly workarounds to get vendor_rust to work.
RUN ln -s /usr/local/cargo $HOME/.cargo && \
    rm -rf /usr/local/cargo/registry && \
    chown -R $USER:$USER /usr/local/cargo/